### ISSUE TITLE
Missed readings alert

### ISSUE THREAD

**Issue by psonnera** [mlukasek/M5_NightscoutMon#10]
I'll try to add it myself but missed readings alerts would be cool, just so that you can sleep without worrying.

**Comment by mlukasek** [comment]
Do you mean a sound alert? There is and optical alert. The box under the time from last data is gery under 5 min, then white from 5-15 min and red when more than 15 minutes.

**Comment by psonnera** [comment]
This is if you want to use it as a real night clock for alarms. If it loses readings (happens: network fails, uploader fails, ...) then you should be advised. I "like" to know when this happens to avoid sleeping through a bad low. Maybe another flag in the .ini for max reading misses (20min?) with a couple of long delay short beeps.

**Comment by mlukasek** [comment]
Missed reading sound allert added. You can adjust it by snd_no_readings key in M5NS.INI (default 20 minutes).
