### ISSUE TITLE
Filter BG/calibration entries

### ISSUE THREAD

**Issue by mlukasek** [mlukasek/M5_NightscoutMon#11]
Need to filter manual entries.
This is a BG measurement add.

**Comment by psonnera** [comment]
218520
sensDev = Manual Entry
sensTime = 1557076342 (JSON 1557076342765) = Sun May  5 19:12:22 2019
sensSgv = 0.00
sensDir = N/A
Sensor: 19:12:22 DST 1
Local: 19:13:3 DST 1
Sensor time difference = 41 sec
Glyk:  0.0 N/A
Last 10 values: 9.89 9.39 9.06 8.83 8.61 8.22 7.50 7.33 7.11 0.00 
Alarm time difference = 1557076383 sec
Snooze time difference = 1800 sec

Yes, filter manual entries might be the fastest

**Comment by psonnera** [comment]
[{"_id":"5ccf197b7dff9aa1b660d431","device":"Manual Entry","type":"mbg","date":1557076342765,"dateString":"2019-05-05T19:12:22.765+0200","mbg":115,"sysTime":"2019-05-05T19:12:22.765+0200"},{"_id":"5ccf18ad7dff9aa1b660d28a","device":"xDrip-Follower","date":1557076141520,"dateString":"2019-05-05T19:09:01.520+0200","sgv":128,"delta":-4.954,"direction":"Flat","type":"sgv","filtered":128000,"unfiltered":128000,"rssi":100,"noise":1,"sysTime":"2019-05-05T19:09:01.520+0200"},{"_id":"5ccf18ad7dff9aa1b660d28c","device":"xDrip-LimiTTer","date":1557075661520,"dateString":"2019-05-05T19:01:01.520+0200","sgv":132,"delta":-2.5,"direction":"Flat","type":"sgv","filtered":132000,"unfiltered":132000,"rssi":100,"noise":1,"sysTime":"2019-05-05T19:01:01.520+0200"},{"_id":"5ccf18ad7dff9aa1b660d28e","device":"xDrip-LimiTTer","date":1557075361520,"dateString":"2019-05-05T18:56:01.520+0200","sgv":135,"delta":-2.5,"direction":"Flat","type":"sgv","filtered":135000,"unfiltered":135000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:56:01.520+0200"},{"_id":"5ccf13f17dff9aa1b660c700","device":"xDrip-Follower","date":1557074930317,"dateString":"2019-05-05T18:48:50.317+0200","sgv":148,"delta":-4.388,"direction":"Flat","type":"sgv","filtered":148000,"unfiltered":148000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:48:50.317+0200"},{"_id":"5ccf155a7dff9aa1b660cb38","device":"xDrip-LimiTTer","date":1557074450317,"dateString":"2019-05-05T18:40:50.317+0200","sgv":155,"delta":-4.375,"direction":"Flat","type":"sgv","filtered":155000,"unfiltered":155000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:40:50.317+0200"},{"_id":"5ccf13f17dff9aa1b660c703","device":"xDrip-LimiTTer","date":1557074150317,"dateString":"2019-05-05T18:35:50.317+0200","sgv":159,"delta":-4.375,"direction":"Flat","type":"sgv","filtered":159000,"unfiltered":159000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:35:50.317+0200"},{"_id":"5ccf13f17dff9aa1b660c702","device":"xDrip-LimiTTer","date":1557073850317,"dateString":"2019-05-05T18:30:50.317+0200","sgv":163,"delta":-4.375,"direction":"Flat","type":"sgv","filtered":163000,"unfiltered":163000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:30:50.317+0200"},{"_id":"5ccf0e557dff9aa1b660b720","device":"xDrip-Follower","date":1557073494585,"dateString":"2019-05-05T18:24:54.585+0200","sgv":169,"delta":-8.994,"direction":"FortyFiveDown","type":"sgv","filtered":169000,"unfiltered":169000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:24:54.585+0200"},{"_id":"5ccf0d297dff9aa1b660b48f","device":"xDrip-Follower","date":1557073194373,"dateString":"2019-05-05T18:19:54.373+0200","sgv":178,"delta":0,"direction":"Flat","type":"sgv","filtered":178000,"unfiltered":178000,"rssi":100,"noise":1,"sysTime":"2019-05-05T18:19:54.373+0200"}]

**Comment by mlukasek** [comment]
Done. BG/calibration/unknown entries are now filtered.
