### ISSUE TITLE
Alarm sound volume set

### ISSUE THREAD

**Issue by mlukasek** [mlukasek/M5_NightscoutMon#12]

**Comment by psonnera** [comment]
You're right setVolume only work with playMusic, let me find some music 😄  https://github.com/nightscout/cgm-remote-monitor/tree/master/static/audio

**Comment by psonnera** [comment]
(Note) audio files necessary are here. https://github.com/earlephilhower/ESP8266Audio/tree/master/src and using this to play it https://github.com/m5stack/M5Stack/tree/master/examples/Advanced/Audio/PlayMP3FromSDToDAC

**Comment by mlukasek** [comment]
Added possibility to change warning sound volume byt warning_volume key in M5NS.INI (0-100, default=20, 0=silent).
Added possibility to change alarm sound volume byt alarm_volume key in M5NS.INI (0-100, default=100, 0=silent).
