### ISSUE TITLE
Right button doesn't turn off

### ISSUE THREAD

**Issue by psonnera** [mlukasek/M5_NightscoutMon#16]
Release May 12th, off button doesn't do anything. That's voluntary?   
if(M5.BtnC.wasPressed()) {
      // M5.Lcd.printf("C");
      Serial.printf("C");
      // M5.setWakeupButton(BUTTON_B_PIN);
      // M5.powerOFF();

**Comment by mlukasek** [comment]
Forgot to ucomment. Corrected.
