### ISSUE TITLE
Incremental snooze

### ISSUE THREAD

**Issue by psonnera** [mlukasek/M5_NightscoutMon#17]
When pressing snooze, value increments by steps of 30 until reaching 180 then returns to 30. This is for high alarms that cannot be fixed in 30 minutes hence forces the user to snooze every 30 min.

**Comment by javporris** [comment]
I was going to propose this same enhancement, I think it's a good idea.

**Comment by mlukasek** [comment]
Implemented in v2020-04-12-01.
