### ISSUE TITLE
loop reboot

### ISSUE THREAD

**Issue by idalioreis** [mlukasek/M5_NightscoutMon#18]
I has able to install the M5 firmware, and change the sd file config to my server, when i start the M5, it see the boot image, find the ip adress well, the next screen will see the hour, nigthscout name and the last difference mg/dl , after that reboot and start again looping.

**Comment by BenjStah** [comment]
I have the same issue. The serial port gives this information:

[HTTP] GET properties...
[HTTP] GET properties... code: 200
Zalozen druhy JSON
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Does anyone know what is the problem?

**Comment by idalioreis** [comment]
I have this error...

> Tuesday, May 21 2019 21:45:52
> Connection done
> [HTTP] begin...
> [HTTP] GET...
> [HTTP] GET... code: 200
> Free Heap = 192928
> sensDev = xDrip-LimiTTer
> sensTime = 1558471259 (JSON 1558471259047) = Tue May 21 21:40:59 2019
> sensSgv = 6.61
> sensDir = FortyFiveDown
> Sensor time: 21:40:59 DST 0
> [HTTP] GET properties...
> [HTTP] GET properties... code: 200
> Zalozen druhy JSON
> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
> Core 1 register dump:
> PC      : 0x400d8a25  PS      : 0x00060630  A0      : 0x800d8ac8  A1      : 0x3ffb19e0  
> A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3f405b40  A5      : 0x3ffc7fd8  
> A6      : 0x00000000  A7      : 0x00000001  A8      : 0x00000001  A9      : 0x3ffb19f0  
> A10     : 0x3ffbecb8  A11     : 0x00040000  A12     : 0x00040000  A13     : 0x3ff65094  
> A14     : 0x3ff65090  A15     : 0x3ff6508c  SAR     : 0x00000008  EXCCAUSE: 0x0000001c  
> EXCVADDR: 0x00000000  LBEG    : 0x400d8131  LEND    : 0x400d813b  LCOUNT  : 0x00000000  
> 
> Backtrace: 0x400d8a25:0x3ffb19e0 0x400d8ac5:0x3ffb1a10 0x400d5665:0x3ffb1a60 0x400d6144:0x3ffb1f80 0x400e1de1:0x3ffb1fb0 0x40089715:0x3ffb1fd0
> 
> Rebooting...
> ets Jun  8 2016 00:22:57

**Comment by idalioreis** [comment]
The last update solve the reboot problem. Thanks

**Comment by mlukasek** [comment]
Bug when reading non existing JSON items. Corrected.
