### ISSUE TITLE
BG readings via Bluetooth

### ISSUE THREAD

**Issue by ghost** [mlukasek/M5_NightscoutMon#19]
This is a great tool! Thanks for your work. As the connection to NS website maybe is instable or server maybe is not online, I would suggest to enhance your tool for grabbing bg values from xdrip via BT and local broadcast. But I'm not a developer...

**Comment by mlukasek** [comment]
Maybe in future, but definitely not soon. I have a lot things to do and this is not a simple task. Sorry.
