### ISSUE TITLE
One time reading from SD

### ISSUE THREAD

**Issue by psonnera** [mlukasek/M5_NightscoutMon#20]
.ini is read from the SD at first start and saved in M5Stack NV memory so that if you remove the SD it will use the saved settings.
PS: haven't even seen if it's feasible with Arduino, but just an idea like that...
PPS: and if you tell me SDs are cheap you're right too.

**Comment by mlukasek** [comment]
Done in release 2021-03-12-01. You have to save the config from web interface manually. I do not want to overwrite the flash everytime you boot using SD card. The SD card has a priority, so you can have one common config in flash and simply change it to another one on SD card, withouth saving config to flash.
