### ISSUE TITLE
Battery indicator

### ISSUE THREAD

**Issue by smog2002** [mlukasek/M5_NightscoutMon#21]
Hi,

at this point I just wanted to thank you, this is really a cool thing you have made there!

Is it possible to install something like a battery indicator?
I don't know if the M5Stack can do that technically, but it would be a nice thing to be able to estimate the battery performance better :)

Thanks!
BR
smog2002

**Comment by mlukasek** [comment]
Newer models of M5Stack support battery info. It is implemented in firmware from 30.5.2019.
