### ISSUE TITLE
config Wifi without SD --IDEA

### ISSUE THREAD

**Issue by idalioreis** [mlukasek/M5_NightscoutMon#27]
I wondering if its possible in future to add wifi AP/server when isnt the sidd on sd card, it will open a web server when acess with smartphone and possible to add the new sidd/password and connect on. 
This will be fine when you have holidays and cant anticipate the sidd/password, so you dont have to walk with computer.
Thanks

**Comment by davmartes** [comment]
This would be very useful. I don’t take my M5 to my business trips abroad because I don’t know the hotels wifi passwords in advance and I don’t want to carry my computer to my trips. I use my iPad instead. That feature would be very useful to me

**Comment by mlukasek** [comment]
Done in release 2021-03-12-01.
