### ISSUE TITLE
Incorrect display on warm-up

### ISSUE THREAD

**Issue by chandler3224** [mlukasek/M5_NightscoutMon#28]
Not sure if this issue is specific to me. 

I currently have a Medtronic 640g with the Guardian 3 sensor. Whenever I connect a new sensor, Nightscout doesn’t have any readings due to the warm-up state. T M5 goes nuts thinking the levels are 0.2. See photos attached. 

I want to start contributing but thought I’d post for now. 

![9A4310F8-092B-4FF4-8B96-FBA447F8458D](https://user-images.githubusercontent.com/851813/62838782-909fcd00-bc78-11e9-830c-e3cc13874f8c.jpeg)
![79366E34-4BBB-4B22-A204-35C946D2DB59](https://user-images.githubusercontent.com/851813/62838783-91386380-bc78-11e9-9d78-984cd3344667.jpeg)

![10CF271C-BE16-46CB-8A28-6E86E6C44B96](https://user-images.githubusercontent.com/851813/62838897-37d13400-bc7a-11e9-9739-835a91d9b551.png)

**Comment by mlukasek** [comment]
Could you please send me your Nightscout URL and possibly grab results of this queries in the time of error?
https://yoursite.herokuapp.com/api/v1/entries.json
https://youriste.herokuapp.com/api/v2/properties/iob,cob,delta,loop,basal
Note: You have to replace yoursite above with correct site URL.

**Comment by chandler3224** [comment]
@mlukasek issue returned today as a calibration was required. Have attached the files!
[Entries.pdf](https://github.com/mlukasek/M5_NightscoutMon/files/3511681/Entries.pdf)
[Entries-calibrated.pdf](https://github.com/mlukasek/M5_NightscoutMon/files/3511689/Entries-calibrated.pdf)
[Properties.pdf](https://github.com/mlukasek/M5_NightscoutMon/files/3511682/Properties.pdf)

**Comment by mlukasek** [comment]
Hello,
thank you for the JSON results. I have checked it and it looks like the Medtronics marks all data as "sgv" and really returns the glycemia 5 mg/dL (0.27 mmol/L). The question is, how should I change the code. How should it behave in your case?
I have just updated the code on GitHub to read only SGV values and omit all callibration, but this will not have impact on your issue, as all readings are marked as SGV and not MBG nor CAL.
Regards
Martin

**Comment by chandler3224** [comment]
Right! Harsh! Looking at the raw JSON there's no other indication that it's in calibration mode, right? Unless there's some extra plugin data that I'm not reading. The uploader app can clearly see it, so I wonder if there's more data I can provide. 

If there *is* more data then I guess the number could be replaced with a hyphen with the pump/sensor status somewhere else. I'll check if there's anything else passed next time it's in calibration.

**Comment by mlukasek** [comment]
Only SGV values are read in release 2019-09-21-01, so this should be solved for now. I plan to add MBG data later.
