### ISSUE TITLE
Why is my screen in inverted colors?

### ISSUE THREAD

**Issue by OpossumGit** [mlukasek/M5_NightscoutMon#31]
I had to change one line in .ino file to 
` M5.Lcd.invertDisplay(1);` 

maybe parameter for invertDisplay could be read from properties file?

**Comment by mlukasek** [comment]
This is not normal. Some hardware fault or library error. M5.Lcd.invertDisplay(0) should be normal display. As more people experience this, I added the invert_display parameter to 2019-10-17-01 release.
