### ISSUE TITLE
time offset by one hour since 20200307 update

### ISSUE THREAD

**Issue by guydavies** [mlukasek/M5_NightscoutMon#37]
hi. I updated over the web client to the latest release yesterday and I noticed that the time was offset by +1 hour on my M5stack since then. I restarted the stack and it didn't change. I also tried setting the configured offset to 0 (I'm in CET so it should be 3600) and that gives the correct display time. I'll leave it like that for now but it looks like some kind of error in time processing.

**Comment by mlukasek** [comment]
What is you dst setting in M5NS.INI?

**Comment by guydavies** [comment]
3600

I presume that's the setting that it will take when DST kicks in? Or is
that a manual setting?

**Comment by mlukasek** [comment]
It is manual setting. You have to change it any time DST gets involved and back. It would be a lot of work to implement all time zones and there is a lot of other more important things to do.

**Comment by guydavies** [comment]
OK. that's weird because I never noticed the time being off before and I've always had both TZ and DST set to 3600. 

I'll close this case. thanks for the great work. it's hugely appreciated.
