### ISSUE TITLE
Vibrations with a material addon for hearing impaired

### ISSUE THREAD

**Issue by Cheun1** [mlukasek/M5_NightscoutMon#43]
Hello Martin.
Is it possible to put vibrations instead of sounds for the hearing impaired, in the m5stack nightcout.
maybee with this addon
https://m5stack.com/products/vibration-motor-unit

Regards

**Comment by mlukasek** [comment]
I will buy one and look at it.

**Comment by Cheun1** [comment]
Thank you for all

**Comment by mlukasek** [comment]
Solved in release v2020-12-06-01.
