### ISSUE TITLE
wifi issue 

### ISSUE THREAD

**Issue by scavenger84** [mlukasek/M5_NightscoutMon#48]
hi im having a problem with loseing wifi signal and dont know how to fix or what going wrong , it just cuts out and system reboots but cant find wifi even tho i got wifi on phone and network name and password is right

**Comment by mlukasek** [comment]
Add restart_at_logged_errors = 0 to you M5NS.INI. This will prevent the device restarting after some number of errors recorded in event log. If you use the RED M5Stack Core, try the black BASIC version, as it has better WiFi reception. Other option is to move the device closer to the WiFi Access Point. I am afraid I cannot do anything about it, this is not a software issue

**Comment by scavenger84** [comment]
I am using the black and grey version 
![Uploading 16009534656376300991527839288205.jpg…]()

**Comment by scavenger84** [comment]
Bought a new wireless access point to see if it will help , was thinking about getting the ethernet part to connect to m5stack but didnt know if would need extra code for it and how its powered then

**Comment by mlukasek** [comment]
Ethernet port will not work, it would require different software. Only closer AP coul help or you can use some WiFi extender. There is only small internal antenna in M5Stack.
