### ISSUE TITLE
Reading data from Dexcom servers

### ISSUE THREAD

**Issue by VolvoGroupAdmin** [mlukasek/M5_NightscoutMon#50]
Investigate the possibility to read data from Dexcom servers and skipping the need for a NS site..

**Comment by Cheun1** [comment]
Cela marche avec sugarmate et le json et trés bien , mettez votre M5 à jour.
![sugarmate](https://user-images.githubusercontent.com/41595891/102595753-6980c780-4118-11eb-93ab-5d38a79df360.PNG)

**Comment by mlukasek** [comment]
Please use sugarmate.io
