### ISSUE TITLE
Works also with M5Stack Core2 ESP32 IoT Development Kit?

### ISSUE THREAD

**Issue by CaptainBalou** [mlukasek/M5_NightscoutMon#59]
Hello,

thanks for your efforts in creating this project!

Does this project also work with the M5Stack Core2 ESP32 IoT Development Kit? The button look different and it is not especially mentioned in the README. The board mentioned in the README is out of stock everywhere (and much more expensive then described in the README I feel) and the Core2 looks very nice and with no buttons which can get unresponsive after a while.
Are there also things possible like a M5Stack model with a luminance sensor to automatically trigger the display brightness somehow?
So interesting this little Nightscout project!

Regards
Marco

**Comment by mlukasek** [comment]
Yes, it is supported, just some features (eg. LED strip connection) are limited. Also the touch buttons does not support some features, such as hold while reset, so it has to be done different way, does not support simple battery back expansion and few more. But generally it works well. The BASIC version is Out Of Stock just momentatrily and there is a lot of selleres selling the BASIC. If you look at Releases, you will see special version for CORE2 there and it is also mentioned in the first sentence on Wiki. Luminance sensor would have to be connected externally, I could consider it, but it will again depend on version used. I plan to implement time configurable brigthness.

**Comment by CaptainBalou** [comment]
I'm sorry to not have seen the wiki comments on this. I'm using Octodroid App to work with githib sometimes and I now realized that this is not showing a wiki tab in any project even if there is one. I now go through the wiki and I assume I will get all answered I need.

Again, thanks for this really nice project.

**Comment by mlukasek** [comment]
No problem, it is hard to make all parts of the code, web and wiki consistent and up to the latest developement. The best way for questions is the Facebook group https://www.facebook.com/groups/606295776549008
