### ISSUE TITLE
silence all devices in local netwoork 

### ISSUE THREAD

**Issue by ghost** [mlukasek/M5_NightscoutMon#62]
It worked and after the update it does not work? I went back to 2020 04 software but it doesn't work either, am I doing something wrong?

**Comment by mlukasek** [comment]
Which version are you using? The latest version should behave OK. At least in my home it works. You must have the same Nightscout URL on all devices that should sync and it takes up to 16s befor it transmits the update. The received should be almost immediate. As UDP (type of packet used) does not have to be absolutely reliable, the UDP packet is send twice more after next 15 and 30 seconds. Or could you have something blocking UDP broadcast packets in your network (some firewall)?

**Comment by ghost** [comment]
Juz jest ok thx .
