### ISSUE TITLE
Revert to original FW

### ISSUE THREAD

**Issue by miguelpruivo** [mlukasek/M5_NightscoutMon#69]
Hi!

Just bought a M5 Stack to give it a try as a NS monitor, however, despite being great, it doesn't add that much value so I'd like to return it, hence, I need to revert it to the original FW that came pre-installed. The thing is... I don't know how/where to do it. It's the M5 Stack Core.

Could you please provide me any insights?

@mlukasek

Thank you!

**Comment by Cheun1** [comment]
Hello you can  with Arduino ......factory test .
