### ISSUE TITLE
Support for the M5StickC - Pico 

### ISSUE THREAD

**Issue by tremor** [mlukasek/M5_NightscoutMon#8]
Do you know the pico version of it:
https://de.aliexpress.com/item/Neue-Ankunft-2019-M5StickC-ESP32-PICO-Mini-IoT-Entwicklung-Bord-Finger-Computer-mit-Farbe-LCD/32985247364.html?spm=a2g0x.10010108.1000013.2.3b121f5e12fuRw&pvid=8e45f361-8fa4-476d-96ea-a612fc7a927d&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.90158.0&scm-url=1007.13339.90158.0&scm_id=1007.13339.90158.0

Can you support the smaller display?

**Comment by psonnera** [comment]
I don't think it has WiFi... maybe wrong...

**Comment by mlukasek** [comment]
I do not have the module, it possibly should not be difficult, it should have a WiFi and everything required,. I do not like the small diplay on it.

**Comment by mlukasek** [comment]
Done as a new repository https://github.com/mlukasek/M5StickC_NightscoutMon
