### ISSUE TITLE
Distribute hex file to simplify users work

### ISSUE THREAD

**Issue by psonnera** [mlukasek/M5_NightscoutMon#9]
Could you release the hex file in Github so that users don't need to setup Arduino with libs, etc.. was thinking about using this: https://forum.arduino.cc/index.php?topic=417659.0

**Comment by psonnera** [comment]
Wrong link above. avrdude I'm not convinced is useable for ESP32. Maybe more like this. https://forum.arduino.cc/index.php?topic=492326.0

**Comment by mlukasek** [comment]
I was thinking about it, I can make binary, but I am not sure how to download it to the M5Stack. If you will find out how, I will add the binary as a release.

**Comment by psonnera** [comment]
Please insert your binaries into a "Binaries" folder
[arduino_build.zip](https://github.com/mlukasek/M5_NightscoutMon/files/3168873/arduino_build.zip)

**Comment by psonnera** [comment]
They are required for M5Burner_NighscoutMon https://github.com/psonnera/M5_NightscoutMon

**Comment by mlukasek** [comment]
Binary files for direct upload by M5Burner added to the project Binaries folder (thanks to Patrick Sonnerat). Complete burner added to GitHub releases.

**Comment by mlukasek** [comment]
Binary files for direct upload by M5Burner added to the project Binaries folder (thanks to Patrick Sonnerat). Complete burner added to GitHub releases.
